### ISSUE TITLE
OSMC

### ISSUE THREAD

**Issue by FastaOne** [macmpi/berryboot-scripts#7]
Is it possible to integrate osmc in berryboot?

https://osmc.tv/

greets

**Comment by macmpi** [comment]
Maybe, but that's not something I have investigated in details yet, and I'm afraid I'm not sure I'll be able to invest time on it soon...
Lots of stuff need to be looked-at to ensure smooth integration (filesystem mapping onto berryboot AUFS layout, update delivery and install, kernel & driver compatibility,etc...).

OSMC is not distributed as squash image, so Pi device will need to convert native image to squash image at install and udpates: not very complex procedure, but it might take time (particularly on lower-end devices). 
Volumio, LibreELEC, and Lakka are distributed as squash, so that part is simpler.

Any big issue with LibreELEC that pushes you to OSMC?

**Comment by FastaOne** [comment]
No, it was just a question. Note, however, that OSMC offers nothing new unlike LibreELEC. Thank you. But yes, how about Lakka. That would be very interesting for me.

**Comment by macmpi** [comment]
Lakka mostly works with available scripts.
Auto-update still fails (last I checked), but this is a general Lakka issue on big downloads, not specific to berryboot integration.

**Comment by FastaOne** [comment]
ok thx, can close
